### ISSUE TITLE
Converting Multi-page PDF

### ISSUE THREAD

**Issue by pr0fsmith** [JCN-9000/pdf2rmnotebook#1]
First, thank you for creating this.  I've been looking for a way to copy and past excerpts from the Bible to my notebooks.  When I tried to convert my PDF Bible, the script only processed the first 2 pages.  is this normal?

**Comment by JCN-9000** [comment]
Version 1.0 only converts first page of file, assuming multi page files are split to single pages and then converted using this script.
Version 1.1 has now ability to convert all pages.
