### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by pr0fsmith** [JCN-9000/pdf2rmnotebook#2]
Got this error for 1.1

evon@evon-ThinkPad-X1-Carbon:~/temp/pdf2rmnotebook$ sudo ./pdf2rmnodebook.sh NET.pdf
./pdf2rmnodebook.sh: 8: Syntax error: newline unexpected

**Comment by JCN-9000** [comment]
Weird. Line 8 is a comment line, it shoud give no errors.
Why are you using sudo to run this script, no need to.
can you run it using   `bash -x ./pdf2rmnodebook.sh NET.pdf`   and post the output somewhere?

**Comment by pr0fsmith** [comment]
This is the output
`./pdf2rmnodebook.sh: line 1: syntax error near unexpected token `newline'
./pdf2rmnodebook.sh: line 1: `<!DOCTYPE html>'
`

**Comment by JCN-9000** [comment]
You downloaded the script wrong: do not use right button / save as from the main page.
Either follow the hyperlinks and use the 'raw' page before saving or better download the [zip](https://github.com/JCN-9000/pdf2rmnotebook/archive/refs/tags/v1.1.zip)/[tar.gz](https://github.com/JCN-9000/pdf2rmnotebook/archive/refs/tags/v1.1.tar.gz) from the [Releases](https://github.com/JCN-9000/pdf2rmnotebook/releases) page. You may also clone the repo.

**Comment by pr0fsmith** [comment]
Works fine now.  I converted the entire Bible and it ended up being 3.5gb lol.

Thanks for the help.

**Comment by JCN-9000** [comment]
Glad it worked. 
Yes, PDF -> drwwj2d -> rM is not a good workflow. 
A full KJ Bible can be converted to a 190MB more or less usable notebook with a day of work.
