### ISSUE TITLE
Convert ReMarkable PDF to Notebook

### ISSUE THREAD

**Issue by Amichayg** [JCN-9000/pdf2rmnotebook#5]
There is a relatively new option to export notebooks to GDrive. However it’s currently not possible to reconvert the exported PDF to Notebook format, I get a scaled down version. 
This could be a feature for editing the notebooks, and then reUploading.

**Comment by JCN-9000** [comment]
Conversion was scaling PDF input files to .75 as usually they are A4 size and this was a best fit to rM page.
Added -s option to scale input. Use -s 1 to keep same input dimensions in the output file if original is 445 x 594 points.
