### ISSUE TITLE
Issues/Question

### ISSUE THREAD

**Issue by Slick2DFish** [JCN-9000/pdf2rmnotebook#7]
Hi I'm trying to get this script to run on windows.

Is there somehow a possibility to  convert it so that it works for windows?
My first attempt was to manually generate the zip file by converting two pdf files and manually adjust the .content file to put them together but this did not work.
My next try was just to get your "Notebook.zip" example -> unzip it and zip it again.
But strangely tis new zipped file had not appear on the remarkable after i have uploaded it via rmapi.
So just unzipping and zipping changes the whole zip? 
Do you have any idea why that is happening?

Update:
I was just stupid. But now I  finally got a working python script that runs on windows like yours :)

**Comment by JCN-9000** [comment]
Glad to hear.

Yes, python script is also a good choice,
